# Generated by Django 6.1 on 2026-08-19 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='agence',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='date_embauche',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='date_essai_fin',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='date_fin_contrat',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='indemnite_km',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='lieu_naissance',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='nationalite',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='num_permis',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='numero_securite_sociale',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='permis_valide',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='prime_anciennete',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='prime_panier',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='salaire_base',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='situation',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='taux_horaire',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='ville',
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('interim', 'Intérim'), ('apprenti', 'Apprenti'), ('stagiaire', 'Stagiaire'), ('auto_entrepreneur', 'Auto-Entrepreneur')], max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('termine', 'Terminé'), ('resilie', 'Résilié'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('date_embauche', models.DateField()),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taux_horaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prime_panier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('indemnite_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prime_anciennete', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='rh.employe')),
            ],
            options={
                'ordering': ['-date_embauche'],
            },
        ),
        migrations.AddField(
            model_name='absence',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences', to='rh.contrat'),
        ),
        migrations.AddField(
            model_name='dpae',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpaes', to='rh.contrat'),
        ),
        migrations.AddField(
            model_name='formation',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='rh.contrat'),
        ),
        migrations.AddField(
            model_name='heuretravail',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heures_travail', to='rh.contrat'),
        ),
        migrations.AddField(
            model_name='notedefrais',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_frais', to='rh.contrat'),
        ),
        migrations.AddField(
            model_name='planningemploye',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plannings', to='rh.contrat'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages', to='rh.contrat'),
        ),
    ]
