# Generated by Django 6.1 on 2026-08-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_remove_employe_actif_remove_employe_agence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpae',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
