# Generated by Django 6.1 on 2026-08-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_prevues', models.FloatField(default=0)),
                ('heures_reelles', models.FloatField(default=0)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(default='Ouvrier', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('plan', 'Plan'), ('rapport', 'Rapport'), ('photo', 'Photographie'), ('courrier', 'Courrier'), ('certificat', 'Certificat'), ('pv', 'Procès-verbal'), ('rfi', "Demande d'information"), ('autre', 'Autre')], max_length=20)),
                ('nom', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='documents_chantier/%Y/%m/')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterventionSousTraitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('montant_estime', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_reel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('planifie', 'Planifiée'), ('encours', 'En cours'), ('termine', 'Terminée'), ('annule', 'Annulée')], default='planifie', max_length=20)),
                ('bon_commande', models.CharField(blank=True, max_length=50)),
                ('facture', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_phase', models.CharField(choices=[('vrd', 'Voirie Réseaux Divers'), ('gros_oeuvre', 'Gros œuvre'), ('second_oeuvre', 'Second œuvre'), ('finitions', 'Finitions'), ('amenagement', 'Aménagement extérieur'), ('terrassement', 'Terrassement'), ('fondation', 'Fondation')], max_length=20)),
                ('ordre', models.IntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin_previsionnelle', models.DateField()),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cout_reel', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taux_avancement', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code chantier')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('type_projet', models.CharField(choices=[('construction', 'Construction neuve'), ('renovation', 'Rénovation'), ('extension', 'Extension'), ('tp', 'Travaux Publics'), ('entretien', 'Entretien'), ('demolition', 'Démolition')], max_length=20, verbose_name='Type')),
                ('statut', models.CharField(choices=[('etude', 'En étude'), ('encours', 'En cours'), ('suspendu', 'Suspendu'), ('termine', 'Terminé'), ('livre', 'Livré')], default='etude', max_length=20, verbose_name='Statut')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin_previsionnelle', models.DateField(verbose_name='Date de fin prévisionnelle')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('duree_jours', models.IntegerField(blank=True, editable=False, null=True)),
                ('budget_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Budget total')),
                ('budget_mo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Budget Main d'œuvre")),
                ('budget_materiaux', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget Matériaux')),
                ('budget_sous_traitance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget Sous-traitance')),
                ('budget_frais_generaux', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget Frais généraux')),
                ('cout_reel_mo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Coût réel MO')),
                ('cout_reel_materiaux', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Coût réel Matériaux')),
                ('cout_reel_sous_traitance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Coût réel Sous-traitance')),
                ('cout_reel_frais_generaux', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Coût réel Frais généraux')),
                ('adresse_chantier', models.TextField(verbose_name='Adresse du chantier')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('coordonnees_gps', models.CharField(blank=True, max_length=100, null=True, verbose_name='Coordonnées GPS')),
                ('taux_avancement', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Taux d'avancement (%)")),
                ('rentabilite_previsionnelle', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Rentabilité prévisionnelle (%)')),
                ('note_qualite', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Note qualité')),
                ('niveau_risque', models.CharField(default='Faible', max_length=10, verbose_name='Niveau de risque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_debut'],
                'permissions': [('can_manage_projets', 'Peut gérer les projets'), ('can_view_all_projets', 'Peut voir tous les projets'), ('can_validate_budget', 'Peut valider les budgets')],
            },
        ),
        migrations.CreateModel(
            name='RapportQuotidien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('conditions_meteo', models.TextField(blank=True)),
                ('effectif_present', models.IntegerField()),
                ('travaux_realises', models.TextField()),
                ('travaux_prevus', models.TextField()),
                ('difficultes', models.TextField(blank=True)),
                ('securite', models.TextField(blank=True)),
                ('materiel_utilise', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('signe_chef_chantier', models.BooleanField(default=False)),
                ('signe_client', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SousTraitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('siret', models.CharField(max_length=14, unique=True)),
                ('type_entreprise', models.CharField(choices=[('tp', 'Travaux Publics'), ('gros_oeuvre', 'Gros œuvre'), ('second_oeuvre', 'Second œuvre'), ('electricite', 'Électricité'), ('plomberie', 'Plomberie'), ('climatisation', 'Climatisation'), ('autre', 'Autre')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('contact_nom', models.CharField(max_length=150)),
                ('contact_telephone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('note', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priorite', models.CharField(choices=[('critique', 'Critique'), ('haute', 'Haute'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], default='moyenne', max_length=20)),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('blocage', 'En blocage'), ('a_valider', 'À valider'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='a_faire', max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin_previsionnelle', models.DateTimeField()),
                ('date_fin_reelle', models.DateTimeField(blank=True, null=True)),
                ('duree_estimee', models.FloatField(help_text='Temps estimé en heures')),
                ('cout_estime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cout_reel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
