# Generated by Django 6.1 on 2026-08-18 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chantiers', '0001_initial'),
        ('crm', '0001_initial'),
        ('rh', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationtache',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.employe'),
        ),
        migrations.AddField(
            model_name='documentchantier',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phase',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phases_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interventionsoustraitant',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chantiers.phase'),
        ),
        migrations.AddField(
            model_name='projet',
            name='agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='users.agence', verbose_name='Agence'),
        ),
        migrations.AddField(
            model_name='projet',
            name='chef_projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_chef', to=settings.AUTH_USER_MODEL, verbose_name='Chef de projet'),
        ),
        migrations.AddField(
            model_name='projet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='crm.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='projet',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phase',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='chantiers.projet'),
        ),
        migrations.AddField(
            model_name='interventionsoustraitant',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions_st', to='chantiers.projet'),
        ),
        migrations.AddField(
            model_name='documentchantier',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='chantiers.projet'),
        ),
        migrations.AddField(
            model_name='rapportquotidien',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_quotidiens', to='chantiers.projet'),
        ),
        migrations.AddField(
            model_name='rapportquotidien',
            name='redacteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interventionsoustraitant',
            name='sous_traitant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='chantiers.soustraitant'),
        ),
        migrations.AddField(
            model_name='tache',
            name='dependances',
            field=models.ManyToManyField(blank=True, to='chantiers.tache'),
        ),
        migrations.AddField(
            model_name='tache',
            name='equipe',
            field=models.ManyToManyField(blank=True, through='chantiers.AffectationTache', to='rh.employe'),
        ),
        migrations.AddField(
            model_name='tache',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='chantiers.phase'),
        ),
        migrations.AddField(
            model_name='tache',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affectationtache',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chantiers.tache'),
        ),
        migrations.AlterUniqueTogether(
            name='rapportquotidien',
            unique_together={('projet', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='affectationtache',
            unique_together={('tache', 'employe')},
        ),
    ]
