# Generated by Django 6.1 on 2026-08-18 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chantiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise'), ('collectivite', 'Collectivité'), ('promoteur', 'Promoteur'), ('bailleur', 'Bailleur social')], max_length=20)),
                ('siret', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='France', max_length=50)),
                ('contact_principal', models.CharField(max_length=150)),
                ('contact_telephone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('numero_compte', models.CharField(blank=True, max_length=20, null=True)),
                ('plafond_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('note', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('objet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_publication', models.DateField()),
                ('date_limite', models.DateField()),
                ('date_soumission', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('en_cours', 'En cours'), ('soumis', 'Soumis'), ('gagne', 'Gagné'), ('perdu', 'Perdu')], default='recu', max_length=20)),
                ('budget_estime', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_soumis', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('documents', models.FileField(blank=True, upload_to='appels_offres/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_offres', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appels_offres', to='crm.client')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('societe', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('contacte', 'Contacté'), ('qualifie', 'Qualifié'), ('devis', 'En devis'), ('perdu', 'Perdu'), ('gagne', 'Gagné')], default='nouveau', max_length=20)),
                ('source', models.CharField(choices=[('site_web', 'Site web'), ('bouche_a_oreille', 'Bouche à oreille'), ('publicite', 'Publicité'), ('salon', 'Salon professionnel'), ('appel', "Appel d'offres"), ('autre', 'Autre')], max_length=20)),
                ('type_travaux', models.CharField(blank=True, max_length=200)),
                ('budget_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('delai_souhaite', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('prochaine_action', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_perte', models.DateField(blank=True, null=True)),
                ('motif_perte', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.client')),
                ('commercial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_interaction', models.CharField(choices=[('appel', 'Appel téléphonique'), ('email', 'Email'), ('rencontre', 'Rencontre'), ('visite_chantier', 'Visite de chantier'), ('reunion', 'Réunion'), ('autre', 'Autre')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duree', models.IntegerField(blank=True, help_text='Durée en minutes', null=True)),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='crm.client')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chantiers.projet')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.lead')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
