# Generated by Django 6.1 on 2026-08-21 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeloffre',
            options={'ordering': ['-date_limite']},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appels_offres', to='users.agence', verbose_name='Agence'),
        ),
        migrations.AddField(
            model_name='client',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='users.agence', verbose_name='Agence'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='users.agence', verbose_name='Agence'),
        ),
        migrations.AddField(
            model_name='lead',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='users.agence', verbose_name='Agence'),
        ),
        migrations.AlterUniqueTogether(
            name='appeloffre',
            unique_together={('agence', 'reference')},
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('agence', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('agence', 'email')},
        ),
    ]
